#! /bin/bash
apt update
apt install nano
apt install ufw
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 5349/tcp
ufw allow 3478/tcp
ufw allow 10000/tcp
ufw enable
hostnamectl set-hostname jitsi.domain
curl https://download.jitsi.org/jitsi-key.gpg.key -o jitsi-key.gpg.key
sudo gpg --output /usr/share/keyrings/jitsi-key.gpg --dearmor jitsi-key.gpg.key
sed -i "deb [signed-by=/usr/share/keyrings/jitsi-key.gpg] https://download.jitsi.org stable/" /etc/apt/sources.list.d/jitsi-stable.list
curl https://prosody.im/files/prosody-debian-packages.key -o prosody-debian-packages.key
sudo gpg --output /usr/share/keyrings/prosody-keyring.gpg --dearmor prosody-debian-packages.key
sed -i "deb [signed-by=/usr/share/keyrings/prosody-keyring.gpg] http://packages.prosody.im/debian jammy main" /etc/apt/sources.list.d/prosody.list
apt update 
apt install jitsi-meet -y
